name: DEPLOY SAFUBASE_UI
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into digitalocean and update repo
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh into
          key: ${{ secrets.SSH_KEY }} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          script: |
            ls
            cd ./apps/safubase-ui
            git fetch
            git pull origin master
            npm install
            npm run build
            pm2 reload safubase-ui --update-env
